export type OrderForm = {
  // id: number;
  country: string;
  cityOfDelivery: string;
  flowerType: string;
  numberOfBoxes: number;
  boxType: string;
  variety: string;
  length: number;
  numberOfStems: number;
  farm: string;
  releaseDate: string;
  purchasePrice: number;
  total: number;
  labeling: string;
  cargoAgencia: string;
  truck: string;
  difference: string;
  salePrice: number;
  totalSales: number;
  awb: string;
  invoice: string;
  invoiceOur: string;
  miami: number;
  finalPriceInMiami: number;
  orderType: string;
  manager: string;
  done: string;
};
