export type ShipmentModel = {
  id: number;
  country: string;
  flowerType: string;
  numberOfBoxes: number;
  boxType: string;
  variety: string;
  length: number;
  numberOfStems: number;
  farm: string;
  releaseDate: string;
  purchasePrice: number;
  total: number;
  labeling: string;
  cargoAgencia: string;
  truck: string;
  difference: string;
  salePrice: number;
  totalSales: number;
  awb: string;
  invoice: string;
  miami: number;
  finalPriceInMiani: number;
  orderType: string;
  manager: string;
  done: string;

  // id: number;
  // pais: string;
  // tpFlor: string;
  // cajas: number;
  // tpCaja: string;
  // variedad: string;
  // long: number;
  // tallos: number;
  // finca: string;
  // fchOut: string;
  // compra: number;
  // ttCompra: number;
  // marca: string;
  // cargoAg: string;
  // truck: string;
  // dif: string;
  // venta: number;
  // ttVenta: number;
  // awb: string;
  // invoice: string;
  // miami: number;
  // ttMiami: number;
  // orden: string;
  // creador: string;
  // ejecutor: string;
};
